### ISSUE TITLE
Disconnecting while MQTTClient.deliver_message() is pending raises IndexError

### ISSUE THREAD

**Issue by zyp** [beerfactory/hbmqtt#106]
If the broker disconnects while `MQTTClient.deliver_message()` is pending and `auto_reconnect` is turned off (and presumably also if `auto_reconnect` fails, but I haven't tested that), `deliver_message()` will raise an `IndexError`:

    WARNING:hbmqtt.client:Disconnected from broker
    DEBUG:transitions.core:Initiating transition from state connected to state disconnected...
    DEBUG:transitions.core:Exiting state connected. Processing callbacks...
    INFO:transitions.core:Exited state connected
    DEBUG:transitions.core:Entering state disconnected. Processing callbacks...
    INFO:transitions.core:Entered state disconnected
    ERROR:asyncio:Task exception was never retrieved
    future: <Task finished coro=<mqtt_loop() done, defined at ./foo.py:19> exception=IndexError('pop from an empty deque',)>
    Traceback (most recent call last):
      File "./foo.py", line 25, in mqtt_loop
        message = await mqtt.deliver_message()
      File "/usr/local/lib/python3.6/site-packages/hbmqtt/client.py", line 334, in deliver_message
        self.client_tasks.pop()
    IndexError: pop from an empty deque

This happens because `cancel_tasks()` called by `handle_connection_close()` pops all tasks from `self.client_tasks` as it cancels them. When the `deliver_task` is cancelled, `deliver_message()` processes it as if it finished normally and tries to pop it from `self.client_tasks` again, resulting in the exception.

I'm not sure what the intended behavior here is. From a user perspective, I think it'd be most useful if `deliver_message()` would just pass on the `ClientException("Connection lost")` from `cancel_tasks()`.

**Comment by zyp** [comment]
I suppose I could, if there's consensus for just letting the `ClientException` get passed on.
