### ISSUE TITLE
asyncio Warning: BrokerProtocolHandler Unhandled exception in reader coro: IncompleteReadError

### ISSUE THREAD

**Issue by nicola-lunghi** [beerfactory/hbmqtt#119]
I get a lot of warning on Ubuntu 17.10 like this

```
[2018-03-30 13:05:45,416] :: WARNING - BrokerProtocolHandler Unhandled exception in reader coro: IncompleteReadError('0 bytes read on a total of 1 expected bytes',)
```

here's the version 
```
 python3 --version
Python 3.6.3
```
```
 pip3 freeze | grep hbmqtt
hbmqtt==0.9.2
```
```
hbmqtt
[2018-03-30 13:05:35,165] :: INFO - Exited state new
[2018-03-30 13:05:35,165] :: INFO - Entered state starting
[2018-03-30 13:05:35,166] :: INFO - Listener 'default' bind to 0.0.0.0:1883 (max_connections=-1)
[2018-03-30 13:05:35,166] :: INFO - Exited state starting
[2018-03-30 13:05:35,166] :: INFO - Entered state started
[2018-03-30 13:05:45,413] :: INFO - Listener 'default': 1 connections acquired
[2018-03-30 13:05:45,413] :: INFO - Connection from 127.0.0.1:49098 on listener 'default'
[2018-03-30 13:05:45,414] :: INFO - Exited state new
[2018-03-30 13:05:45,414] :: INFO - Entered state connected
[2018-03-30 13:05:45,416] :: WARNING - BrokerProtocolHandler Unhandled exception in reader coro: IncompleteReadError('0 bytes read on a total of 1 expected bytes',)
[2018-03-30 13:05:45,416] :: INFO - Exited state connected
[2018-03-30 13:05:45,417] :: INFO - Entered state disconnected
[2018-03-30 13:05:45,417] :: INFO - Listener 'default': 0 connections acquired

```
```
hbmqtt_pub --url "mqtt://localhost:1883" -t "test/sensor1" -m "ciao"
[2018-03-30 13:05:45,409] :: INFO - hbmqtt_pub/13323-nicklang-laptop Connecting to broker
[2018-03-30 13:05:45,415] :: INFO - Exited state new
[2018-03-30 13:05:45,415] :: INFO - Entered state connected
[2018-03-30 13:05:45,415] :: INFO - hbmqtt_pub/13323-nicklang-laptop Publishing to 'test/sensor1'
[2018-03-30 13:05:45,416] :: INFO - Exited state connected
[2018-03-30 13:05:45,416] :: INFO - Entered state disconnected
[2018-03-30 13:05:45,416] :: INFO - hbmqtt_pub/13323-nicklang-laptop Disconnected from broker
```
the broker work fine but I get warning for every sent message

**Comment by romancardenas** [comment]
I experience the same issue on MacOS 10.13.3
As you said, the broker works fine, and messages are received by subscribed processes.

**Comment by Kriechi** [comment]
I'm getting the same error. macos 10.13.4 as client and with a linux server, both with hbmqtt 0.9.2.

**Comment by joopy** [comment]
getting the same error, looking for a solution.

**Comment by ivan-antonyuck** [comment]
I'm experiencing the same issue reading from the broker (emqtt) in loop, the problem arises after about 1700-1800 messages in consequent read;
Subscriber code:
`
from hbmqtt.client import MQTTClient, QOS_0
import asyncio
loop = asyncio.get_event_loop()

@asyncio.coroutine
def consume():
    C = MQTTClient()
    yield from C.connect('mqtt://192.168.0.2/')
    yield from C.subscribe([
        ('a/b',QOS_0)
    ])
    try:
        while 1:
            yield from C.deliver_message()
    finally:
        yield from C.unsubscribe(['a/b'])
        yield from C.disconnect()

loop.run_until_complete(consume())
`

**Comment by arnulfojr** [comment]
I'm having the same issue in 0.9.4

**Comment by joopy** [comment]
I 'fixed' it by not useing hbmqtt anymore. Now using mosquitto.

**Comment by Simon-L** [comment]
I traced back this error until I found out that 0.9.4 actually works fine if you use the "taboo" broker from the samples:
`python3 broker_taboo.py`
Use it along with the `taboo` publish and subscribe samples.

I got confused by assuming from the Quick Start page in the documentation that `hbmqtt` would work indistinctly with all the `hbmqtt_*` scripts, turns out it's a bit more picky than that!

**Comment by arnulfojr** [comment]
@Simon-L so we need to use the taboo thinggy?

I turned into rabbitMQ with mqtt plugin and Paho's mqtt but originally I was looking for an asyncio implementation, is that then working for you?

**Comment by arnulfojr** [comment]
I discovered that the client is as well experiencing the same problem...

**Comment by Merwenus** [comment]
Same problem for me in Home Assistant, any fix yet?
2018-09-24 17:21:41 WARNING (MainThread) [hbmqtt.mqtt.protocol.handler] BrokerProtocolHandler Unhandled exception in reader coro: IncompleteReadError('0 bytes read on a total of 1 expected bytes',)

**Comment by JohannesBauer97** [comment]
Same for me:
BrokerProtocolHandler Unhandled exception in reader coro: IncompleteReadError('0 bytes read on a total of 1 expected bytes',)

**Comment by anthonyray** [comment]
Same issue here !

**Comment by ramonpoca** [comment]
I've traced the error a bit. Added a logging.exception that shows:
```
ERROR:hbmqtt.mqtt.protocol.handler:0 bytes read on a total of 1 expected bytes
Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.6/site-packages/hbmqtt/mqtt/protocol/handler.py", line 373, in _
reader_loop
    keepalive_timeout, loop=self._loop)
  File "/usr/local/miniconda3/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/miniconda3/lib/python3.6/site-packages/hbmqtt/mqtt/packet.py", line 104, in from_stream
    byte1 = yield from read_or_raise(reader, 1)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/hbmqtt/codecs.py", line 52, in read_or_raise
    data = yield from reader.read(n)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/hbmqtt/adapters.py", line 146, in read
    data = yield from self._reader.readexactly(n)
  File "/usr/local/miniconda3/lib/python3.6/asyncio/streams.py", line 672, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 1 expected bytes
WARNING:hbmqtt.mqtt.protocol.handler:ClientProtocolHandler Unhandled exception in reader coro: IncompleteReadError('0 bytes read on a total of 1 expected bytes',)
```

**Comment by ramonpoca** [comment]
Keeping with the tracing, I've dumped it happening with wireshark. Hex dump follows. 
After the last `c0 00` packet sent by hbmqtt, the server responds with a TCP RST (reset).
Server is mosquitto 1.5.3 macos (homebrew).

```
00000000  10 23 00 04 4d 51 54 54  04 02 00 09 00 17 68 62   .#..MQTT ......hb
00000010  6d 71 74 74 2f 47 38 6a  34 38 42 46 50 6d 4e 6f   mqtt/G8j 48BFPmNo
00000020  60 30 45 30 7a                                     `0E0z
    00000000  20 02 00 00                                         ...
00000025  82 06 00 01 00 01 23 02                            ......#. 
    00000004  90 03 00 01 02                                     .....
0000002D  c0 00                                              ..
    00000009  d0 00                                              ..
    0000000B  34 24 00 11 2f 66 69 72  65 62 61 73 65 2f 63 6f   4$../fir ebase/co
    0000001B  6e 74 72 6f 6c 00 01 7b  22 72 65 6c 6f 61 64 22   ntrol..{ "reload"
    0000002B  3a 20 33 37 30 7d                                  : 370}
0000002F  50 02 00 01                                        P...
    00000031  62 02 00 01                                        b...
00000033  70 02 00 01                                        p...
00000037  c0 00                                              ..
00000000  10 23 00 04 4d 51 54 54  04 02 00 09 00 17 68 62   .#..MQTT ......hb
00000010  6d 71 74 74 2f 47 38 6a  34 38 42 46 50 6d 4e 6f   mqtt/G8j 48BFPmNo
00000020  60 30 45 30 7a                                     `0E0z
    00000000  20 02 00 00                                         ...
00000025  82 06 00 01 00 01 23 02                            ......#. 
    00000004  90 03 00 01 02                                     .....
0000002D  c0 00                                              ..
    00000009  d0 00                                              ..
    0000000B  34 24 00 11 2f 66 69 72  65 62 61 73 65 2f 63 6f   4$../fir ebase/co
    0000001B  6e 74 72 6f 6c 00 01 7b  22 72 65 6c 6f 61 64 22   ntrol..{ "reload"
    0000002B  3a 20 33 37 30 7d                                  : 370}
0000002F  50 02 00 01                                        P...
    00000031  62 02 00 01                                        b...
00000033  70 02 00 01                                        p...
00000037  c0 00                                              ..

```

**Comment by ramonpoca** [comment]
Ok, think I've found out:
- Client is running in a mixed async/sync environment.
- A reload process lasting more than 10 seconds was blocking processing, and so hbmqtt wasn't able to send the keepalive PING on time.
- *Solution/hotfix*: Increase the client keepalive to a larger value from the default 10 seconds.

**Comment by ohminy** [comment]
How could i change the keepalive time in HBMQTT??

**Comment by DallasO** [comment]
I'm seeing this warning from my MQTT client, but it isn't affecting anything - messages are still making it through.

I'm using eclipse/paho.mqtt.python and tried their sync/async methods, and the keepalive is already defaulted to 60 seconds. So my only other try would be @ramonpoca's second point, but I'm not sure how to change that.

**Comment by skewty** [comment]
@ramonpoca I don't think that's it.

I get that error running the broker as such:

```python
import asyncio
import logging
from hbmqtt.broker import Broker

logging.basicSetup(level=logging.INFO)
logger = logging.getLogger('broker')


def main():
    loop = asyncio.get_event_loop()
    config = {
        'listeners': {
            'default': {
                'type': 'tcp',
            },
            'combox': {
                'bind': '127.0.0.1:1883',
            }
        }
    }
    broker = Broker(config=config, plugin_namespace='invalid.namespace')
    loop.create_task(broker.start())
    try:
        logger.info('Broker listening on {}'.format(config['listeners']['combox']['bind']))
        loop.run_forever()
    except KeyboardInterrupt:
        pass


if __name__ == '__main__':
    main()
```

It occurs after just one call to publish() from a system test we have where two clients subscribe to a common stream and publish a single, short message to each other and disconnect (test takes around 1 second).

**Comment by caseybrichardson** [comment]
Just thought I'd throw out that I'm also experiencing this issue. I have a couple async python applications and found this project. Integrated really smoothly, but now I'm having issues with this framework and using persistent sessions. I'm only using the client but several applications all begin to face this issue after running for a while and after a few connects/disconnects. The only solution I've found for this is to restart the application with a new client_id which is something I'd like to avoid as persistent sessions are required for data persistence reasons.

**Comment by 26labs** [comment]
My trialling of hbmqtt as broker seems to reflect what others have seen - use the broker-taboo config plugin and then using MQTTBox or own python code on macOS (10.15.3) and messages will be seen and stored by broker. Also own python code, following the examples, will get messages registered with broker. So right now hbmqtt would seem to be good if one needs a 100% python type of setup for mqtt broker and clients. There is an issue mentioned at the HomeAssistant site about memory consumption after 20k messages which is of concern. I will test further -  i have been using mosquitto in my project for 5 years for its "industrial strength" and small footprint but have always wanted a python option (even if it means volume-based restart cycles) for my solution to make easier to setup demos on new machines.
