### ISSUE TITLE
Exceptions on each message received

### ISSUE THREAD

**Issue by ozroc** [beerfactory/hbmqtt#19]
> [2016-02-04 15:43:13,171] :: ERROR - Task exception was never retrieved
> future: <Task finished coro=<stream_connected() done, defined at /.../hbmqtt/broker.py:318> exception=ConnectionResetError('Connection lost',)>
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
>     result = coro.send(None)
>   File "/.../hbmqtt/broker.py", line 320, in stream_connected
>     yield from self.client_connected(listener_name, StreamReaderAdapter(reader), StreamWriterAdapter(writer))
>   File "/.../hbmqtt/broker.py", line 427, in client_connected
>     yield from writer.close()
>   File "/.../hbmqtt/adapters.py", line 168, in close
>     yield from self._writer.drain()
>   File "/usr/lib/python3.5/asyncio/streams.py", line 313, in drain
>     yield from self._protocol._drain_helper()
>   File "/usr/lib/python3.5/asyncio/streams.py", line 194, in _drain_helper
>     raise ConnectionResetError('Connection lost')
> ConnectionResetError: Connection lost

And after closing the server:

> Exception ignored in: <generator object BrokerProtocolHandler.get_next_pending_subscription at 0x7f3aef258780>
> Traceback (most recent call last):
>   File "/.../hbmqtt/mqtt/protocol/broker_handler.py", line 89, in get_next_pending_subscription
>   File "/usr/lib/python3.5/asyncio/queues.py", line 170, in get
>   File "/usr/lib/python3.5/asyncio/futures.py", line 227, in cancel
>   File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
>   File "/usr/lib/python3.5/asyncio/base_events.py", line 447, in call_soon
>   File "/usr/lib/python3.5/asyncio/base_events.py", line 456, in _call_soon
>   File "/usr/lib/python3.5/asyncio/base_events.py", line 284, in _check_closed
> RuntimeError: Event loop is closed

**Comment by njouanin** [comment]
Could you give some details of the context when this error happened. "Connection lost" messages means that broker's connection to the client has been closed unexpectedly. 
Could you also specify the version of htbmqtt you're using. Also the python version.

**Comment by ozroc** [comment]
Sure.

I'm just running hbmqtt server and from the same machine I'm running a subscriber: 
```
$ hbmqtt_sub --url mqtt://localhost:1883 -t test/
hello world
```
and publishing a test message:
```
$ hbmqtt_pub --url mqtt://localhost:1883 -t test/ --clean-session -r -m "hello world"
[2016-02-05 12:56:52,274] :: INFO - hbmqtt_pub/10168-bluetc-Aspire-V3-772G Connecting to broker
[2016-02-05 12:56:52,280] :: INFO - hbmqtt_pub/10168-bluetc-Aspire-V3-772G Publishing to 'test/'
[2016-02-05 12:56:52,281] :: INFO - hbmqtt_pub/10168-bluetc-Aspire-V3-772G Disconnected from broker
```
This is the complete output in my server:
```
$ hbmqtt
[2016-02-05 12:56:42,430] :: INFO - Listener 'default' bind to 0.0.0.0:1883 (max_connecionts=-1)
[2016-02-05 12:56:45,773] :: INFO - Listener 'default': 1 connections acquired
[2016-02-05 12:56:45,773] :: INFO - Connection from 127.0.0.1:36901 on listener 'default'
[2016-02-05 12:56:52,278] :: INFO - Listener 'default': 2 connections acquired
[2016-02-05 12:56:52,278] :: INFO - Connection from 127.0.0.1:36902 on listener 'default'
[2016-02-05 12:56:52,279] :: WARNING - Delete session : session hbmqtt_pub/10168-bluetc-Aspire-V3-772G doesn't exist
[2016-02-05 12:56:52,283] :: ERROR - Task exception was never retrieved
future: <Task finished coro=<stream_connected() done, defined at /home/bluetc/.virtualenvs/mqtt/lib/python3.5/site-packages/hbmqtt-0.6-py3.5.egg/hbmqtt/broker.py:318> exception=ConnectionResetError('Connection lost',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/bluetc/.virtualenvs/mqtt/lib/python3.5/site-packages/hbmqtt-0.6-py3.5.egg/hbmqtt/broker.py", line 320, in stream_connected
    yield from self.client_connected(listener_name, StreamReaderAdapter(reader), StreamWriterAdapter(writer))
  File "/home/bluetc/.virtualenvs/mqtt/lib/python3.5/site-packages/hbmqtt-0.6-py3.5.egg/hbmqtt/broker.py", line 427, in client_connected
    yield from writer.close()
  File "/home/bluetc/.virtualenvs/mqtt/lib/python3.5/site-packages/hbmqtt-0.6-py3.5.egg/hbmqtt/adapters.py", line 168, in close
    yield from self._writer.drain()
  File "/usr/lib/python3.5/asyncio/streams.py", line 313, in drain
    yield from self._protocol._drain_helper()
  File "/usr/lib/python3.5/asyncio/streams.py", line 194, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
[2016-02-05 12:56:55,800] :: ERROR - Task exception was never retrieved
future: <Task finished coro=<stream_connected() done, defined at /home/bluetc/.virtualenvs/mqtt/lib/python3.5/site-packages/hbmqtt-0.6-py3.5.egg/hbmqtt/broker.py:318> exception=ConnectionResetError('Connection lost',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/bluetc/.virtualenvs/mqtt/lib/python3.5/site-packages/hbmqtt-0.6-py3.5.egg/hbmqtt/broker.py", line 320, in stream_connected
    yield from self.client_connected(listener_name, StreamReaderAdapter(reader), StreamWriterAdapter(writer))
  File "/home/bluetc/.virtualenvs/mqtt/lib/python3.5/site-packages/hbmqtt-0.6-py3.5.egg/hbmqtt/broker.py", line 427, in client_connected
    yield from writer.close()
  File "/home/bluetc/.virtualenvs/mqtt/lib/python3.5/site-packages/hbmqtt-0.6-py3.5.egg/hbmqtt/adapters.py", line 168, in close
    yield from self._writer.drain()
  File "/usr/lib/python3.5/asyncio/streams.py", line 313, in drain
    yield from self._protocol._drain_helper()
  File "/usr/lib/python3.5/asyncio/streams.py", line 194, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
^C[2016-02-05 12:56:59,181] :: INFO - Broker closed
[2016-02-05 12:56:59,199] :: ERROR - Task was destroyed but it is pending!
task: <Task pending coro=<Broker._broadcast_loop() running at /home/bluetc/.virtualenvs/mqtt/lib/python3.5/site-packages/hbmqtt-0.6-py3.5.egg/hbmqtt/broker.py:652> wait_for=<Future pending cb=[Task._wakeup()]>>
[2016-02-05 12:56:59,199] :: ERROR - Task was destroyed but it is pending!
task: <Task pending coro=<ProtocolHandler.mqtt_deliver_next_message() running at /home/bluetc/.virtualenvs/mqtt/lib/python3.5/site-packages/hbmqtt-0.6-py3.5.egg/hbmqtt/mqtt/protocol/handler.py:457> wait_for=<Future pending cb=[Task._wakeup()]>>
[2016-02-05 12:56:59,199] :: ERROR - Task was destroyed but it is pending!
task: <Task pending coro=<BrokerProtocolHandler.get_next_pending_subscription() running at /home/bluetc/.virtualenvs/mqtt/lib/python3.5/site-packages/hbmqtt-0.6-py3.5.egg/hbmqtt/mqtt/protocol/broker_handler.py:89> wait_for=<Future pending cb=[Task._wakeup()]>>
[2016-02-05 12:56:59,199] :: ERROR - Task was destroyed but it is pending!
task: <Task pending coro=<BrokerProtocolHandler.get_next_pending_unsubscription() running at /home/bluetc/.virtualenvs/mqtt/lib/python3.5/site-packages/hbmqtt-0.6-py3.5.egg/hbmqtt/mqtt/protocol/broker_handler.py:94> wait_for=<Future pending cb=[Task._wakeup()]>>
[2016-02-05 12:56:59,199] :: ERROR - Task was destroyed but it is pending!
task: <Task pending coro=<ProtocolHandler.mqtt_deliver_next_message() running at /home/bluetc/.virtualenvs/mqtt/lib/python3.5/site-packages/hbmqtt-0.6-py3.5.egg/hbmqtt/mqtt/protocol/handler.py:457> wait_for=<Future pending cb=[Task._wakeup()]>>
Exception ignored in: <generator object ProtocolHandler.mqtt_deliver_next_message at 0x7f2b8702c1a8>
Traceback (most recent call last):
  File "/home/bluetc/.virtualenvs/mqtt/lib/python3.5/site-packages/hbmqtt-0.6-py3.5.egg/hbmqtt/mqtt/protocol/handler.py", line 457, in mqtt_deliver_next_message
  File "/usr/lib/python3.5/asyncio/queues.py", line 170, in get
  File "/usr/lib/python3.5/asyncio/futures.py", line 227, in cancel
  File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
  File "/usr/lib/python3.5/asyncio/base_events.py", line 447, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 456, in _call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 284, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <generator object BrokerProtocolHandler.get_next_pending_subscription at 0x7f2b8702c200>
Traceback (most recent call last):
  File "/home/bluetc/.virtualenvs/mqtt/lib/python3.5/site-packages/hbmqtt-0.6-py3.5.egg/hbmqtt/mqtt/protocol/broker_handler.py", line 89, in get_next_pending_subscription
  File "/usr/lib/python3.5/asyncio/queues.py", line 170, in get
  File "/usr/lib/python3.5/asyncio/futures.py", line 227, in cancel
  File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
  File "/usr/lib/python3.5/asyncio/base_events.py", line 447, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 456, in _call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 284, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <generator object BrokerProtocolHandler.get_next_pending_unsubscription at 0x7f2b8702c150>
Traceback (most recent call last):
  File "/home/bluetc/.virtualenvs/mqtt/lib/python3.5/site-packages/hbmqtt-0.6-py3.5.egg/hbmqtt/mqtt/protocol/broker_handler.py", line 94, in get_next_pending_unsubscription
  File "/usr/lib/python3.5/asyncio/queues.py", line 170, in get
  File "/usr/lib/python3.5/asyncio/futures.py", line 227, in cancel
  File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
  File "/usr/lib/python3.5/asyncio/base_events.py", line 447, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 456, in _call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 284, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <generator object ProtocolHandler.mqtt_deliver_next_message at 0x7f2b8702cf10>
Traceback (most recent call last):
  File "/home/bluetc/.virtualenvs/mqtt/lib/python3.5/site-packages/hbmqtt-0.6-py3.5.egg/hbmqtt/mqtt/protocol/handler.py", line 457, in mqtt_deliver_next_message
  File "/usr/lib/python3.5/asyncio/queues.py", line 170, in get
  File "/usr/lib/python3.5/asyncio/futures.py", line 227, in cancel
  File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
  File "/usr/lib/python3.5/asyncio/base_events.py", line 447, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 456, in _call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 284, in _check_closed
RuntimeError: Event loop is closed
[2016-02-05 12:56:59,200] :: ERROR - Task was destroyed but it is pending!
task: <Task pending coro=<BrokerProtocolHandler.get_next_pending_subscription() running at /home/bluetc/.virtualenvs/mqtt/lib/python3.5/site-packages/hbmqtt-0.6-py3.5.egg/hbmqtt/mqtt/protocol/broker_handler.py:89> wait_for=<Future pending cb=[Task._wakeup()]>>
[2016-02-05 12:56:59,200] :: ERROR - Task was destroyed but it is pending!
task: <Task pending coro=<BrokerProtocolHandler.get_next_pending_unsubscription() running at /home/bluetc/.virtualenvs/mqtt/lib/python3.5/site-packages/hbmqtt-0.6-py3.5.egg/hbmqtt/mqtt/protocol/broker_handler.py:94> wait_for=<Future pending cb=[Task._wakeup()]>>
Exception ignored in: <generator object BrokerProtocolHandler.get_next_pending_subscription at 0x7f2b8702cc50>
Traceback (most recent call last):
  File "/home/bluetc/.virtualenvs/mqtt/lib/python3.5/site-packages/hbmqtt-0.6-py3.5.egg/hbmqtt/mqtt/protocol/broker_handler.py", line 89, in get_next_pending_subscription
  File "/usr/lib/python3.5/asyncio/queues.py", line 170, in get
  File "/usr/lib/python3.5/asyncio/futures.py", line 227, in cancel
  File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
  File "/usr/lib/python3.5/asyncio/base_events.py", line 447, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 456, in _call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 284, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <generator object BrokerProtocolHandler.get_next_pending_unsubscription at 0x7f2b8702ce60>
Traceback (most recent call last):
  File "/home/bluetc/.virtualenvs/mqtt/lib/python3.5/site-packages/hbmqtt-0.6-py3.5.egg/hbmqtt/mqtt/protocol/broker_handler.py", line 94, in get_next_pending_unsubscription
  File "/usr/lib/python3.5/asyncio/queues.py", line 170, in get
  File "/usr/lib/python3.5/asyncio/futures.py", line 227, in cancel
  File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
  File "/usr/lib/python3.5/asyncio/base_events.py", line 447, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 456, in _call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 284, in _check_closed
RuntimeError: Event loop is closed
```

I've found the same issues with both master and develop branches.
My python version is 3.5.1

**Comment by njouanin** [comment]
OK, I can reproduce it, so I can investigate.

**Comment by njouanin** [comment]
Fixed issue on the develop branch. Could you have a test ? (works for me)

**Comment by ozroc** [comment]
Yes, it's fixed.
Thank you!
