### ISSUE TITLE
hbmqtt broker is broken 

### ISSUE THREAD

**Issue by cristi-zz** [beerfactory/hbmqtt#191]
I tried to run hbmqtt as a broker, then pub/sub on some channel (3 different consoles).
This is what I got in the broker's console. There was NO message in the sub console, and no error in pub console.

```python3.7/site-packages/hbmqtt/utils.py:51: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(stream)
[2019-11-04 12:31:40,564] :: WARNING - 'topic-check' section not found in context configuration
[2019-11-04 12:31:40,565] :: INFO - Exited state new
[2019-11-04 12:31:40,565] :: INFO - Entered state starting
[2019-11-04 12:31:40,565] :: INFO - Listener 'default' bind to 0.0.0.0:1883 (max_connections=-1)
[2019-11-04 12:31:40,565] :: INFO - Exited state starting
[2019-11-04 12:31:40,565] :: INFO - Entered state started
[2019-11-04 12:31:57,821] :: INFO - Listener 'default': 1 connections acquired
[2019-11-04 12:31:57,821] :: INFO - Connection from 127.0.0.1:35025 on listener 'default'
[2019-11-04 12:31:57,823] :: INFO - Exited state new
[2019-11-04 12:31:57,823] :: INFO - Entered state connected
[2019-11-04 12:31:57,825] :: ERROR - Task exception was never retrieved
future: <Task finished coro=<Broker.stream_connected() done, defined at /home/visoft/miniconda3/envs/py7/lib/python3.7/site-packages/hbmqtt/broker.py:341> exception=AttributeError("'TopicTabooPlugin' object has no attribute 'topic_config'")>
Traceback (most recent call last):
  File "/home/visoft/miniconda3/envs/py7/lib/python3.7/site-packages/hbmqtt/broker.py", line 343, in stream_connected
    yield from self.client_connected(listener_name, StreamReaderAdapter(reader), StreamWriterAdapter(writer))
  File "/home/visoft/miniconda3/envs/py7/lib/python3.7/site-packages/hbmqtt/broker.py", line 469, in client_connected
    result = yield from self.add_subscription(subscription, client_session)
  File "/home/visoft/miniconda3/envs/py7/lib/python3.7/site-packages/hbmqtt/broker.py", line 624, in add_subscription
    permitted = yield from self.topic_filtering(session, topic=a_filter)
  File "/home/visoft/miniconda3/envs/py7/lib/python3.7/site-packages/hbmqtt/broker.py", line 586, in topic_filtering
    filter_plugins=topic_plugins)
  File "/home/visoft/miniconda3/envs/py7/lib/python3.7/site-packages/hbmqtt/plugins/manager.py", line 207, in map_plugin_coro
    return (yield from self.map(self._call_coro, coro_name, *args, **kwargs))
  File "/home/visoft/miniconda3/envs/py7/lib/python3.7/site-packages/hbmqtt/plugins/manager.py", line 181, in map
    ret_list = yield from asyncio.gather(*tasks, loop=self._loop)
  File "/home/visoft/miniconda3/envs/py7/lib/python3.7/site-packages/hbmqtt/plugins/manager.py", line 193, in _call_coro
    return (yield from coro)
  File "/home/visoft/miniconda3/envs/py7/lib/python3.7/asyncio/coroutines.py", line 120, in coro
    res = func(*args, **kw)
  File "/home/visoft/miniconda3/envs/py7/lib/python3.7/site-packages/hbmqtt/plugins/topic_checking.py", line 27, in topic_filtering
    filter_result = super().topic_filtering(*args, **kwargs)
  File "/home/visoft/miniconda3/envs/py7/lib/python3.7/site-packages/hbmqtt/plugins/topic_checking.py", line 13, in topic_filtering
    if not self.topic_config:
AttributeError: 'TopicTabooPlugin' object has no attribute 'topic_config'
[2019-11-04 12:32:03,815] :: WARNING - BrokerProtocolHandler Unhandled exception in reader coro: IncompleteReadError('0 bytes read on a total of 1 expected bytes')
```
Thank you!

**Comment by cristi-zz** [comment]
Found this: https://github.com/home-assistant/home-assistant/issues/16708#issuecomment-422902879

So, from python, I started the server using this configuration:

```@asyncio.coroutine
def broker_coro():
    config = {
        'listeners': {
            'default': {
                'max-connections': 50000,
                'bind': '0.0.0.0:1883',
                'type': 'tcp',
            },
            'ws-1': {
                'bind': '0.0.0.0:8080',
                'type': 'ws',
            },
        },
        'auth': {
            'allow-anonymous': True
        },
        'plugins': ['auth_anonymous'],
        'topic-check': {
            'enabled': True,
            'plugins': ['topic_taboo'],
        },
    }
    broker = Broker(config=config)
    yield from broker.start()
```
instead of the example configuration listed here: https://hbmqtt.readthedocs.io/en/latest/references/broker.html#broker-configuration

And it works.

Why I don't close this bug, is because starting hbmqtt from command line DOES NOT create, by default, a usable configuration. 

Cheers!

**Comment by Kren** [comment]
This is exactly what I needed. I added this to config and it worked:
`"auth": { 
    "allow-anonymous": True
}, 
"topic-check": {
    "enabled": True,
    "plugins": ['topic_taboo']
}`
