### ISSUE TITLE
Mosquitto CA test file expired?

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [beerfactory/hbmqtt#230]
Hey @njouanin,
I ran the nosetests locally and ran into an SSL error:
```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: CA certificate key too weak (_ssl.c:1051)
asyncio: ERROR: SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7ff59855fba8>
transport: <_SelectorSocketTransport closing fd=150 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/home/marius/.pyenv/versions/3.7.1/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/home/marius/.pyenv/versions/3.7.1/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/home/marius/.pyenv/versions/3.7.1/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: CA certificate key too weak (_ssl.c:1051)
hbmqtt.client: WARNING: MQTT connection failed: SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: CA certificate key too weak (_ssl.c:1051)')
```
Does the `tests/mosquitto.org.crt` maybe need to be renewed?

Best regards
Marius

**Comment by HerrMuellerluedenscheid** [comment]
I can confirm that the certificate is expired. I'm going to open a MR that downloads the certificate on the fly.

**Comment by HerrMuellerluedenscheid** [comment]
#232 resolves this issue. Thus, closing.
