### ISSUE TITLE
Error with recent websockets package

### ISSUE THREAD

**Issue by jiargei** [beerfactory/hbmqtt#250]
Running hbmqtt I get the following error.

Traceback (most recent call last):
  File "/home/mqtt/.local/bin/hbmqtt", line 33, in <module>
    sys.exit(load_entry_point('hbmqtt==0.9.6', 'console_scripts', 'hbmqtt')())
  File "/home/mqtt/.local/bin/hbmqtt", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/mqtt/.local/lib/python3.9/site-packages/scripts/broker_script.py", line 23, in <module>
    from hbmqtt.broker import Broker
  File "/home/mqtt/.local/lib/python3.9/site-packages/hbmqtt/broker.py", line 15, in <module>
    from hbmqtt.session import Session
  File "/home/mqtt/.local/lib/python3.9/site-packages/hbmqtt/session.py", line 8, in <module>
    from hbmqtt.mqtt.publish import PublishPacket
  File "/home/mqtt/.local/lib/python3.9/site-packages/hbmqtt/mqtt/__init__.py", line 5, in <module>
    from hbmqtt.mqtt.packet import (
  File "/home/mqtt/.local/lib/python3.9/site-packages/hbmqtt/mqtt/packet.py", line 8, in <module>
    from hbmqtt.adapters import ReaderAdapter, WriterAdapter
  File "/home/mqtt/.local/lib/python3.9/site-packages/hbmqtt/adapters.py", line 6, in <module>
    from websockets.protocol import WebSocketCommonProtocol
ModuleNotFoundError: No module named 'websockets.protocol'

Current Workaround:

`sed -i 's/from websockets.protocol import WebSocketCommonProtocol/from websockets.**legacy.**protocol import WebSocketCommonProtocol/' ~/.local/lib/python3.9/site-packages/hbmqtt/adapters.py`

**Comment by edmaher** [comment]
The change was made in websockets v 9.0, so version 8.1 is the last one that works by default

**Comment by csyyysc** [comment]
Facing this error message with newly created virtual env:

```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/test/bin/hbmqtt", line 5, in <module>
    from scripts.broker_script import main
  File "/opt/anaconda3/envs/test/lib/python3.10/site-packages/scripts/broker_script.py", line 23, in <module>
    from hbmqtt.broker import Broker
  File "/opt/anaconda3/envs/test/lib/python3.10/site-packages/hbmqtt/broker.py", line 15, in <module>
    from hbmqtt.session import Session
  File "/opt/anaconda3/envs/test/lib/python3.10/site-packages/hbmqtt/session.py", line 8, in <module>
    from hbmqtt.mqtt.publish import PublishPacket
  File "/opt/anaconda3/envs/test/lib/python3.10/site-packages/hbmqtt/mqtt/__init__.py", line 5, in <module>
    from hbmqtt.mqtt.packet import (
  File "/opt/anaconda3/envs/test/lib/python3.10/site-packages/hbmqtt/mqtt/packet.py", line 8, in <module>
    from hbmqtt.adapters import ReaderAdapter, WriterAdapter
  File "/opt/anaconda3/envs/test/lib/python3.10/site-packages/hbmqtt/adapters.py", line 6, in <module>
    from websockets.protocol import WebSocketCommonProtocol
ImportError: cannot import name 'WebSocketCommonProtocol' from 'websockets.protocol' (/opt/anaconda3/envs/test/lib/python3.10/site-packages/websockets/protocol.py)
```

Looks like the dependency on websockets is not bound with, and causes error whenever install this package.
