### ISSUE TITLE
hbmqtt does not react correctly to illegal protocol levels

### ISSUE THREAD

**Issue by ckrey** [beerfactory/hbmqtt#34]
> [MQTT-3.1.2-2]
> The Server MUST respond to the CONNECT Packet with a CONNACK return code 0x01 (unacceptable protocol level) and then disconnect the Client if the Protocol Level is not supported by the Server.

> [MQTT-3.2.2-5]
> If a server sends a CONNACK packet containing a non-zero return code it MUST then close the Network Connection.

```
[2016-04-05 08:40:20,721] :: INFO - Connection from 127.0.0.1:60442 on listener 'default'
[2016-04-05 08:40:20,723] :: ERROR - Task exception was never retrieved
future: <Task finished coro=<stream_connected() done, defined at /usr/local/lib/python3.5/site-packages/hbmqtt/broker.py:319> exception=AttributeError("'ConnectVariableHeader' object has no attribute 'protocol_level'",)>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/usr/local/lib/python3.5/site-packages/hbmqtt/broker.py", line 321, in stream_connected
    yield from self.client_connected(listener_name, StreamReaderAdapter(reader), StreamWriterAdapter(writer))
  File "/usr/local/lib/python3.5/site-packages/hbmqtt/broker.py", line 336, in client_connected
    handler, client_session = yield from BrokerProtocolHandler.init_from_connect(reader, writer, self.plugins_manager, loop=self._loop)
  File "/usr/local/lib/python3.5/site-packages/hbmqtt/mqtt/protocol/broker_handler.py", line 147, in init_from_connect
    connect.variable_header.protocol_level)
AttributeError: 'ConnectVariableHeader' object has no attribute 'protocol_level'
```

**Comment by ckrey** [comment]
confirmed
