### ISSUE TITLE
hbmqtt does not fetch exception when zero length payload is sent

### ISSUE THREAD

**Issue by ckrey** [beerfactory/hbmqtt#35]
```
[2016-04-05 08:46:57,759] :: INFO - Listener 'default' bind to 0.0.0.0:1883 (max_connecionts=-1)
[2016-04-05 08:47:07,140] :: INFO - Listener 'default': 1 connections acquired
[2016-04-05 08:47:07,140] :: INFO - Connection from 127.0.0.1:60542 on listener 'default'
[2016-04-05 08:47:08,131] :: ERROR - Task exception was never retrieved
future: <Task finished coro=<stream_connected() done, defined at /usr/local/lib/python3.5/site-packages/hbmqtt/broker.py:319> exception=KeyError('MQTTClient',)>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/usr/local/lib/python3.5/site-packages/hbmqtt/broker.py", line 321, in stream_connected
    yield from self.client_connected(listener_name, StreamReaderAdapter(reader), StreamWriterAdapter(writer))
  File "/usr/local/lib/python3.5/site-packages/hbmqtt/broker.py", line 466, in client_connected
    self.retain_message(client_session, app_message.topic, app_message.data, app_message.qos)
  File "/usr/local/lib/python3.5/site-packages/hbmqtt/broker.py", line 543, in retain_message
    del self._retained_messages[topic_name]
KeyError: 'MQTTClient'
^C[20
```

**Comment by njouanin** [comment]
Can you provide the CONNECT packet details for this test case ?

**Comment by ckrey** [comment]
Sorry for the confustion: The error actually happens when sending a zero length payload with retained = YES (to delete another retained message) and the topic is not retained
```
2016-04-11 23:09:42:971 xctest[34156:3625115] [MQTTTestHelpers] sending: 03 q0 r1 d0 m0 (12) <000a4d51 5454436c 69656e74>
```

**Comment by ckrey** [comment]
I cannot confirm this being fixed:

Recreate with

```
$ mosquitto_pub -t 'MQTTClient/r1q0' -m 'abc' -d  -V mqttv311 -r
$ mosquitto_pub -t 'MQTTClient/r1q0' -n -d  -V mqttv311 -r
$ mosquitto_pub -t 'MQTTClient/r1q0' -n -d  -V mqttv311 -r
```

```
[2016-05-23 23:05:37,266] :: ERROR :: asyncio :: Task exception was never retrieved
future: <Task finished coro=<stream_connected() done, defined at /usr/local/lib/python3.5/site-packages/hbmqtt/broker.py:319> exception=KeyError('MQTTClient/-[MQTTClientPublishTests testPublish_r1_q0_zeroLengthPayload]',)>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/usr/local/lib/python3.5/site-packages/hbmqtt/broker.py", line 321, in stream_connected
    yield from self.client_connected(listener_name, StreamReaderAdapter(reader), StreamWriterAdapter(writer))
  File "/usr/local/lib/python3.5/site-packages/hbmqtt/broker.py", line 466, in client_connected
    self.retain_message(client_session, app_message.topic, app_message.data, app_message.qos)
  File "/usr/local/lib/python3.5/site-packages/hbmqtt/broker.py", line 543, in retain_message
    del self._retained_messages[topic_name]
KeyError: 'MQTTClient/-[MQTTClientPublishTests testPublish_r1_q0_zeroLengthPayload]'
```

**Comment by ckrey** [comment]
confirmed
