### ISSUE TITLE
Broker startup failed: an integer is required (got type str)

### ISSUE THREAD

**Issue by andreynech** [beerfactory/hbmqtt#42]
Python 3.5.1+ (default, Mar 30 2016, 22:46:26)
Ubuntu 16.04 LTS
hbmqtt Installed either with pip3 or from latest github sources.

Attempt to run hbmqtt causes the error below. It seams like casting port to int, i.e. int(port), in broker.py at line 256 fixes this issue. However, I did not check if there are any other places where similar problem may occur.

[2016-06-10 14:35:13,583] :: ERROR - Broker startup failed: an integer is required (got type str)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/hbmqtt/broker.py", line 258, in start
    loop=self._loop)
  File "/usr/lib/python3.5/asyncio/streams.py", line 116, in start_server
    return (yield from loop.create_server(factory, host, port, **kwds))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 949, in create_server
    sock.bind(sa)
TypeError: an integer is required (got type str)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/hbmqtt", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/scripts/broker_script.py", line 72, in main
    loop.run_until_complete(broker.start())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 361, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 331, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1298, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 308, in _wakeup
    self._step()
  File "/usr/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/hbmqtt/broker.py", line 280, in start
    raise BrokerException("Broker instance can't be started: %s" % e)
hbmqtt.broker.BrokerException: Broker instance can't be started: an integer is required (got type str)

**Comment by njouanin** [comment]
Can you provide your configuration file ?

**Comment by andreynech** [comment]
This error happens even if running without -c option. But sure, here is my (in this case unused) configuration file:

listeners:
    default:
        type: tcp
        bind: 0.0.0.0:1883
    my-ws-1:
        bind: 0.0.0.0:9001
        type: ws
sys_interval: 20

**Comment by andreynech** [comment]
sorry, the formatting was lost somehow. Here it is attached.

[hbmqtt.zip](https://github.com/beerfactory/hbmqtt/files/309096/hbmqtt.zip)

**Comment by njouanin** [comment]
I can't reproduce this error. Nevertheless, I've commited a check to detect invalid port value.

**Comment by irfanka** [comment]
I'm experiencing a similar issue.

At first, I tried to create a Broker instance, without passing a config (i.e. using the defaults), and this exception was raised:
`hbmqtt.broker.BrokerException: Listener config not found invalid: 'listeners'`

so I tried passing the following config dict to the Broker constructor:
`
 config = {                                                                       
     'listeners': {                                                               
         'default': {                                                             
             'bind': '127.0.0.1:1883',                                            
             'type': 'tcp'                                                                             
         }                                                                        
     }                                                                            
 } 
`

and received the following exception:

`hbmqtt.broker.BrokerException: Broker instance can't be started: an integer is required (got type str)`

**Comment by njouanin** [comment]
Have you tried with latest version (0.7.3) ?
