### ISSUE TITLE
error message from tests 

### ISSUE THREAD

**Issue by attdona** [beerfactory/hbmqtt#51]
Running hbmqtt tests there are a lot of error messages, for example:

pytest -s test_client.py::MQTTClientTest::test_ping
============================================================================================ test session starts ============================================================================================
platform linux -- Python 3.4.3, pytest-3.0.2, py-1.4.31, pluggy-0 

========================================================================================= 1 passed in 0.11 seconds ==========================================================================================
[2016-09-07 10:14:43,964] asyncio {base_events.py:1008} ERROR - Task was destroyed but it is pending!
task: <Task pending coro=<stream_connected() running at /home/adona/dev/hbmqtt/hbmqtt/broker.py:336> wait_for=<Future pending cb=[Task._wakeup()]>>
[2016-09-07 10:14:43,964] asyncio {base_events.py:1008} ERROR - Task was destroyed but it is pending!
task: <Task pending coro=<wait_disconnect() running at /home/adona/dev/hbmqtt/hbmqtt/mqtt/protocol/broker_handler.py:44> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.4/asyncio/tasks.py:399]>
[2016-09-07 10:14:43,964] asyncio {base_events.py:1008} ERROR - Task was destroyed but it is pending!
task: <Task pending coro=<get_next_pending_subscription() running at /home/adona/dev/hbmqtt/hbmqtt/mqtt/protocol/broker_handler.py:89> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.4/asyncio/tasks.py:399]>
[2016-09-07 10:14:43,964] asyncio {base_events.py:1008} ERROR - Task was destroyed but it is pending!
task: <Task pending coro=<get_next_pending_unsubscription() running at /home/adona/dev/hbmqtt/hbmqtt/mqtt/protocol/broker_handler.py:94> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.4/asyncio/tasks.py:399]>
[2016-09-07 10:14:43,964] asyncio {base_events.py:1008} ERROR - Task was destroyed but it is pending!
task: <Task pending coro=<mqtt_deliver_next_message() running at /home/adona/dev/hbmqtt/hbmqtt/mqtt/protocol/handler.py:462> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.4/asyncio/tasks.py:399]>
Exception ignored in: [2016-09-07 10:14:43,965] asyncio {base_events.py:1008} ERROR - Task was destroyed but it is pending!
task: <Task pending coro=<_reader_loop() running at /home/adona/dev/hbmqtt/hbmqtt/mqtt/protocol/handler.py:373> wait_for=<Future finished result=None>>
[2016-09-07 10:14:43,965] hbmqtt.mqtt.protocol.handler {handler.py:432} WARNING - BrokerProtocolHandler Unhandled exception in reader coro: GeneratorExit()
[2016-09-07 10:14:43,965] hbmqtt.mqtt.protocol.handler {broker_handler.py:55} DEBUG - Client disconnecting
[2016-09-07 10:14:43,965] hbmqtt.mqtt.protocol.handler {broker_handler.py:57} DEBUG - Setting waiter result to None
Exception ignored in: <generator object _reader_loop at 0x7fd424ec1288>
Traceback (most recent call last):
  File "/home/adona/dev/hbmqtt/hbmqtt/mqtt/protocol/handler.py", line 436, in _reader_loop
    yield from self.handle_connection_closed()
  File "/home/adona/dev/hbmqtt/hbmqtt/mqtt/protocol/broker_handler.py", line 62, in handle_connection_closed
    yield from self.handle_disconnect(None)
  File "/usr/lib/python3.4/asyncio/coroutines.py", line 141, in coro
    res = func(*args, **kw)
  File "/home/adona/dev/hbmqtt/hbmqtt/mqtt/protocol/broker_handler.py", line 58, in handle_disconnect
    self._disconnect_waiter.set_result(disconnect)
  File "/usr/lib/python3.4/asyncio/futures.py", line 339, in set_result
    self._schedule_callbacks()
  File "/usr/lib/python3.4/asyncio/futures.py", line 243, in _schedule_callbacks
    self._loop.call_soon(callback, self)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 427, in call_soon
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 436, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.4/asyncio/base_events.py", line 265, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

How to fix that?
greetings
Attilio

**Comment by nShade** [comment]
There is a workaround to avoid this. You just need cancel all the tasks that for some reason are still pending. For instance, after invoking Broker.shutdown() I do following:
```python
# this is because my event loop runs in separate thread
f = asyncio.run_coroutine_threadsafe(broker.shutdown(), loop)

    while not f.done():
        pass

all_tasks = asyncio.Task.all_tasks(loop=self._loop)
pending_tasks = list([task for task in all_tasks if task._state == asyncio.futures._PENDING])

while len(pending_tasks) != 0:
    for task in pending_tasks:
        self._loop.call_soon_threadsafe(task.cancel)

    all_tasks = asyncio.Task.all_tasks(loop=self._loop)
    pending_tasks = list([task for task in all_tasks if task._state == asyncio.futures._PENDING])
```

**Comment by attdona** [comment]
Thanks nShade!

After some investigations my conclusion is that the errors occours because the test use the same loop for client and for broker: the loop is closed while coroutine Broker.client_connected is waiting for tasks to close and thus a RuntimeError('Event loop is closed') is fired

the workaround that works for me is to add a sleep in the test function:

    def test_ping(self):
        @asyncio.coroutine
        def test_coro():
            try:
                broker = Broker(broker_config, plugin_namespace="hbmqtt.test.plugins")
                yield from broker.start()
                client = MQTTClient()
                ret = yield from client.connect('mqtt://localhost/')
                self.assertIsNotNone(client.session)
                yield from client.ping()
                yield from client.disconnect()
                yield from broker.shutdown()
                yield from asyncio.sleep(0.1)  ### <------ ADD THIS
                future.set_result(True)
            except Exception as ae:
                future.set_exception(ae)

        future = asyncio.Future(loop=self.loop)
        self.loop.run_until_complete(test_coro())
        
        if future.exception():
            raise future.exception()
 
I'm not able to see if exists some better fix.
