### ISSUE TITLE
MQTT errors with Home-Assistant

### ISSUE THREAD

**Issue by arsaboo** [beerfactory/hbmqtt#52]
I am trying to add HBMQTT to [Home-Assistant](https://home-assistant.io). I used the default config as indicated [here](https://home-assistant.io/components/mqtt/):
```
mqtt:
  embedded:
```
I get the following error:
```
homeassistant.bootstrap: Invalid config for [mqtt]: expected dict for dictionary value @ data['mqtt']['embedded']. Got None
```
@balloob suggested adding `{}` after `embedded`, so I modified the config to:
```
mqtt:
  embedded: {}
```
Now, I get the following errors:
```
16-09-07 21:33:57 homeassistant.components.mqtt.server: Error initializing MQTT server
Traceback (most recent call last):
  File "/home/hass/.homeassistant/deps/hbmqtt/broker.py", line 184, in _build_listeners_config
    listeners_config = broker_config['listeners']
KeyError: 'listeners'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/components/mqtt/server.py", line 53, in start
    loop.run_until_complete(start_server)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 271, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.4/asyncio/base_events.py", line 244, in run_forever
    self._run_once()
  File "/usr/lib/python3.4/asyncio/base_events.py", line 1081, in _run_once
    handle._run()
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 237, in _step
    result = next(coro)
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/components/mqtt/server.py", line 23, in broker_coro
    broker = Broker(config, loop)
  File "/home/hass/.homeassistant/deps/hbmqtt/broker.py", line 156, in __init__
    self._build_listeners_config(self.config)
  File "/home/hass/.homeassistant/deps/hbmqtt/broker.py", line 191, in _build_listeners_config
    raise BrokerException("Listener config not found invalid: %s" % ke)
hbmqtt.broker.BrokerException: Listener config not found invalid: 'listeners'
16-09-07 21:33:57 homeassistant.components.mqtt: Unable to start broker and auto-configure MQTT.
16-09-07 21:33:57 homeassistant.bootstrap: component mqtt failed to initialize
16-09-07 21:33:57 asyncio: Task exception was never retrieved
future: <Task finished coro=<broker_coro() done, defined at /srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/components/mqtt/server.py:19> exception=BrokerException("Listener config not found invalid: 'listeners'",)>
Traceback (most recent call last):
  File "/home/hass/.homeassistant/deps/hbmqtt/broker.py", line 184, in _build_listeners_config
    listeners_config = broker_config['listeners']
KeyError: 'listeners'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/components/mqtt/server.py", line 53, in start
    loop.run_until_complete(start_server)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 271, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.4/asyncio/base_events.py", line 244, in run_forever
    self._run_once()
  File "/usr/lib/python3.4/asyncio/base_events.py", line 1081, in _run_once
    handle._run()
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 237, in _step
    result = next(coro)
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/components/mqtt/server.py", line 23, in broker_coro
    broker = Broker(config, loop)
  File "/home/hass/.homeassistant/deps/hbmqtt/broker.py", line 156, in __init__
    self._build_listeners_config(self.config)
  File "/home/hass/.homeassistant/deps/hbmqtt/broker.py", line 191, in _build_listeners_config
    raise BrokerException("Listener config not found invalid: %s" % ke)
hbmqtt.broker.BrokerException: Listener config not found invalid: 'listeners'
```

**Comment by balloob** [comment]
This is not an issue for hbmqtt but for Home Assistant
