### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by feliperian** [beerfactory/hbmqtt#77]
File "hbmqtt\plugins\manager.py", line 142, in clean_fired_events
    self._fired_events.remove(task)
ValueError: list.remove(x): x not in list

The error is caused because of the except treat as "KeyError" and not "ValueError"

**Comment by dmadhavaraj** [comment]
I am getting the same error . Below is my Python version . Please let us know if you have workaround for the same.

**Python 3.6.1** (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32

```
File "c:\python\lib\site-packages\hbmqtt\plugins\manager.py", line 142, in clean_fired_events
    self._fired_events.remove(task)
ValueError: list.remove(x): x not in list
[2017-07-19 11:55:44,280] :: ERROR - Exception in callback PluginManager.fire_event.<locals>.clean_fired_events(<Task finishe...> result=None>) at c:\python\lib\site-packages\hbmqtt\plugins\manager.py:140
handle: <Handle PluginManager.fire_event.<locals>.clean_fired_events(<Task finishe...> result=None>) at c:\python\lib\site-packages\hbmqtt\plugins\manager.py:140>
Traceback (most recent call last):
  File "c:\python\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "c:\python\lib\site-packages\hbmqtt\plugins\manager.py", line 142, in clean_fired_events
    self._fired_events.remove(task)
ValueError: list.remove(x): x not in list
[2017-07-19 11:55:44,282] :: ERROR - Exception in callback PluginManager.fire_event.<locals>.clean_fired_events(<Task finishe...> result=None>) at c:\python\lib\site-packages\hbmqtt\plugins\manager.py:140
handle: <Handle PluginManager.fire_event.<locals>.clean_fired_events(<Task finishe...> result=None>) at c:\python\lib\site-packages\hbmqtt\plugins\manager.py:140>
Traceback (most recent call last):
  File "c:\python\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "c:\python\lib\site-packages\hbmqtt\plugins\manager.py", line 142, in clean_fired_events
    self._fired_events.remove(task)
ValueError: list.remove(x): x not in list
```

**Comment by krautcat** [comment]
Well, I have the same error under Python 3.5.2 and Python 3.6.2. It doesn't depend whether I'm using my own broker or distributed py package `hbmqtt` broker executable.
`Python 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609] on linux`
`Python 3.6.2 (default, Jul 21 2017, 11:23:24) [GCC 5.4.0 20160609] on linux`

**Comment by ipfans** [comment]
@njouanin hi, can we release a minor version to fix this issue?

**Comment by njouanin** [comment]
sure !
i'll try to do it in the coming days.

**Comment by njouanin** [comment]
Done : https://github.com/beerfactory/hbmqtt/releases/tag/0.9.1
