### ISSUE TITLE
hbmqtt do not support the latest transitions.

### ISSUE THREAD

**Issue by zaazbb** [beerfactory/hbmqtt#80]
after upgrate transitions to 0.5.3, met a error.
`Warning (from warnings module):
  File "C:\Python36\lib\asyncio\base_events.py", line 510
    source=self)
ResourceWarning: unclosed event loop <_WindowsSelectorEventLoop running=False closed=False debug=False>
Traceback (most recent call last):
  File "C:\Users\jf\Desktop\mqtt_subscriber.py", line 38, in <module>
    loop.run_until_complete(uptime_coro())
  File "C:\Python36\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "C:\Users\jf\Desktop\mqtt_subscriber.py", line 11, in uptime_coro
    C = MQTTClient()
  File "C:\Python36\lib\site-packages\hbmqtt\client.py", line 112, in __init__
    self.plugins_manager = PluginManager('hbmqtt.client.plugins', context)
  File "C:\Python36\lib\site-packages\hbmqtt\plugins\manager.py", line 55, in __init__
    self._load_plugins(namespace)
  File "C:\Python36\lib\site-packages\hbmqtt\plugins\manager.py", line 66, in _load_plugins
    plugin = self._load_plugin(ep)
  File "C:\Python36\lib\site-packages\hbmqtt\plugins\manager.py", line 73, in _load_plugin
    plugin = ep.load(require=True)
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2304, in load
    self.require(*args, **kwargs)
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2327, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 862, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (transitions 0.5.3 (c:\python36\lib\site-packages), Requirement.parse('transitions==0.2.5'))`

**Comment by jodal** [comment]
This should be fixed by pull request #82.

**Comment by jodal** [comment]
Pull request #82 have now been merged, do this issue should be resolved with the next hbmqtt release.

**Comment by jodal** [comment]
This should be resolved with the release of v0.9.1 half a year ago.
